# /home/senaex/.config/tmuxinator/anyconfig.yml
name: anyconfig
root: /opt/anyconfig

windows:
  - main:
      layout: d392,211x52,0,0[211x36,0,0,5,211x15,0,37,6]
      panes:
        - cd go && vim main.go
        - cd go && clear
  - dotfiles: cd /home/ALEX/dotfiles/.anyconfig && clear
  - docker: cd docker && clear
  - old:
      layout: d392,211x52,0,0[211x36,0,0,5,211x15,0,37,6]
      panes:
        - cd old && vim .
        - cd old && clear
