dependencies:
  os:
    - arch
install:
  pkg:
    - git
    - gcc
    - icu
    - ripgrep
    - npm
  mkdir:
    - "{home}/.config"
  backup:
    - "{home}/.config/nvim"
  ln:
    - Linking nvim folder | {repo}/nvim > {home}/.config/

dependencies:
  os:
    - debian
install:
  pkg:
    - git
    - gcc
    - ripgrep
    - npm
  mkdir:
    - "{home}/.config"
  backup:
    - "{home}/.config/nvim/"
  ln:
    - Linking nvim folder | {repo}/nvim > {home}/.config/
