dependencies:
  task:
    - zsh/zsh
    - zsh/ohmyzsh
install:
  backup:
    - "{home}/.rc-temp"
    - "{home}/.zshrc"
    - "/usr/local/zsh/oh-my-zsh/themes/senaex.zsh-theme"
  mkdir:
    - "{home}/.rc"
  ln:
    - Linking .zshrc | {repo}/zsh/.zshrc > {home}
    - Linking AddIn-Folder | {repo}/zsh/.rc-temp > {home}
    - Linking theme senaex | {repo}/zsh/senaex.zsh-theme > /usr/local/zsh/oh-my-zsh/themes
