bind -n M-F11 \
    run-shell "tmux set -g @tmux_power_theme $(tmux show-option -gv @color_active)" \;\
    run-shell '~/.tmux/plugins/tmux-power/tmux-power.tmux' \;\
    refresh-client -S

# When the outer session tells us to sleep (M-F12)
bind -n M-F12 \
    run-shell "tmux set -g @tmux_power_theme $(tmux show-option -gv @color_inactive)" \;\
    run-shell '~/.tmux/plugins/tmux-power/tmux-power.tmux' \;\
    refresh-client -S

